let form = document.querySelector("#form")
let nome = document.querySelector("#name")
let email = document.querySelector("#email")
let cep = document.querySelector("#cep")
let numero = document.querySelector("#number")
let cidade = document.querySelector("#city")
let rua = document.querySelector("#street")
let estado = document.querySelector("#state")
